#!/usr/bin/env ruby
require 'pry'
require 'open-uri'
require 'nokogiri'
require_relative '../lib/trope.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/trope_finder.rb'

module Mod
  class Error < StandardError; end
end